### ISSUE TITLE
Feature request: PayPal-Bitcoin Option.

### ISSUE THREAD

**Issue by ghost** [wdehoog/donnie#18]
it would be good an option to be able to contribute with a project.

**Comment by wdehoog** [comment]
Thanks for the suggestion but I will not do so. Since I only invest my time and do not need to pay equipment or other necessities I do not want any monetary donation. It is a hobby that I am able to do because others are investing time as well. Like you for example.

If someone wants to show appreciation for Donnie by donating then maybe they can help support openrepos.net.

**Comment by Caballlero** [comment]
please sailor consider this to aboutPage.

**Comment by ghost** [comment]
Thanks anyway.
